branch-defaults:
  main:
    environment: dc-env
global:
  application_name: beiwe-application
  default_ec2_keyname: beiwe.cer
  default_platform: 64bit Amazon Linux 2018.03 v2.9.4 running Python 3.6
  default_region: us-west-2
  profile: eb-cli
  sc: git
