branch-defaults:
  main:
    environment: beiwe-env
    group_suffix: null
global:
  application_name: beiwe-application
  branch: main
  default_ec2_keyname: beiwe.cer
  default_platform: 64bit Amazon Linux 2018.03 v2.9.4 running Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
