branch-defaults:
  main:                            # You can change "master" to any branch name
    environment: dev-env
global:
  application_name: beiwe-application
  default_ec2_keyname: beiwe.cer  # Same as in global_configuration.json
  default_platform: 64bit Amazon Linux 2018.03 v2.9.4 running Python 3.6
  default_region: us-west-2                # Same as in global_configuration.json
  profile: eb-cli                             # this name just needs to match a profile declared in ~/.aws/
  sc: git