branch-defaults:
  main:
    environment: beiwe-env
    group_suffix: null
global:
  application_name: beiwe-application
  branch: main
  default_ec2_keyname: beiwe.cer
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application